language: go

before_install: go get github.com/mattn/goveralls

matrix:
  include:
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=on
      install: true
    - go: "tip"
      env: GO111MODULE=on
      install: true

script:
  - go test -v --coverprofile=cover.out ./...
  - goveralls --coverprofile=cover.out --service=travis-ci
