name: Main
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.13.x"
          - "1.14.x"
          - "1.15.x"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{matrix.go}}
      - name: Check out code
        uses: actions/checkout@v2.3.4
      - name: Download modules
        run: go mod download
      - name: Test
        run: go test -v --coverprofile=cover.out ./...
      - name: Upload coverage profile
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: cover.out
